#!/usr/bin/env python3
"""Build the Undraft Claude Project prompt from its two sources.

The Project (the translation tool this repo started as) takes the system
prompt plus the voice rules. Those rules live in claude.md, which has since
grown into the blog pipeline's rulebook: tags, rotation lists, inbox rules,
review references. Pasting all of it into the Project fed the tool rules
that mean nothing there. This picks the voice sections by heading and writes
undraft-project-prompt.md, the one file to paste.

  build_project_prompt.py           rewrite undraft-project-prompt.md
  build_project_prompt.py --check   exit 1 if it is out of date (CI)
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SYSTEM = os.path.join(ROOT, "undraft-system-prompt.md")
RULES = os.path.join(ROOT, "claude.md")
OUT = os.path.join(ROOT, "undraft-project-prompt.md")

# claude.md sections that are about how Undraft writes, not how the blog runs.
SECTIONS = [
    "What This Project Is",
    "Voice Models",
    "AI Writing Tells: The Kill List",
    "What Good Undraft Output Looks Like",
    "Operating Rules",
    "Drafting Rules",
]
HEADER = ("<!-- Generated by scripts/build_project_prompt.py from "
          "undraft-system-prompt.md and the voice sections of claude.md. "
          "Edit those, then rerun the script. Paste this whole file into the "
          "Undraft Claude Project. -->\n\n")


def system_prompt(text):
    """Everything below the first `---` line of undraft-system-prompt.md."""
    parts = re.split(r"(?m)^---\s*$", text, maxsplit=1)
    if len(parts) != 2:
        raise SystemExit("undraft-system-prompt.md has no --- line")
    return parts[1].strip()


def sections(text, names):
    """The named `## ` sections of claude.md, in the order given."""
    found = {}
    for block in re.split(r"(?m)^(?=## )", text):
        m = re.match(r"## (.+)", block)
        if m:
            found[m.group(1).strip()] = block.strip().rstrip("-").strip()
    missing = [n for n in names if n not in found]
    if missing:
        raise SystemExit(f"claude.md is missing sections: {missing}")
    return [found[n] for n in names]


def build():
    with open(SYSTEM, encoding="utf-8") as f:
        sp = system_prompt(f.read())
    with open(RULES, encoding="utf-8") as f:
        rules = sections(f.read(), SECTIONS)
    return HEADER + sp + "\n\n---\n\n# Voice rules\n\n" + "\n\n".join(rules) + "\n"


def main():
    out = build()
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != out:
            print("undraft-project-prompt.md is out of date: run python3 scripts/build_project_prompt.py")
            return 1
        print("undraft-project-prompt.md is up to date")
        return 0
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({len(out)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
